### ISSUE TITLE
Not able to move binary

### ISSUE THREAD

**Issue by atsuya** [zeit/now-app#108]
Error: Command failed: mv /var/folders/pw/y7pxyvkx7mg87kqjj5yfg9xh0000gn/T/tmp-1065VOo5nu2mdPep/now-macos /usr/local/bin/now

**Comment by leo** [comment]
@atsuya Where are your binaries located? Where are you expecting the `now` binary to get moved to by the application?

**Comment by leo** [comment]
Will be solved with https://github.com/zeit/now-app/issues/177
