### ISSUE TITLE
Unhandled error appeared

### ISSUE THREAD

**Issue by shawninder** [zeit/now-app#130]
```
Error: ENOSPC: no space left on device, write
    at Error (native)
```

I got his error today. I've been trying to deploy https://github.com/vigour-io/imaginate with docker with no success (the first things that happen are logs but only the first one shows, still trying to figure out the problem here). I suppose this is related...

If I find anything else I will post here.

**Comment by shawninder** [comment]
btw it's possible that it is my computer who has no space left, I'm really short on space these days

**Comment by leo** [comment]
Yep, it's definitely your device.

There's sadly nothing we can do here. I highly recommend upgrading it! 😊
