### ISSUE TITLE
Could not create deployment

### ISSUE THREAD

**Issue by muhamed-didovic** [zeit/now-app#207]
Hi,

When I use your desktop app I got this: Error: timeout of 30000ms exceeded

Using command line I see there are a lot of errors during npm install and npm start commands.
This is the id: Td7ggCEvBhZxD5gDxiJIIvhw

**Comment by leo** [comment]
If there are errors during `npm install` and `npm start`, it's probably related to your project. Does it work with `now`?

**Comment by muhamed-didovic** [comment]
Hi,

Thanks for quick response.
So, it is simple app with mongodb, it works ok locally and on heroku too.
Can you check the logs?

**Comment by leo** [comment]
Please ask support@zeit.co for help on this. It's definitely not related to Now.app 😊
