### ISSUE TITLE
Could not create deployment

### ISSUE THREAD

**Issue by michaelwschultz** [zeit/now-app#81]
Error: Request failed with status code 413

Just tried to upload an image to test the "share" ability by dragging it to the menu icon.

**Comment by leo** [comment]
@rase- See. Looks like the same problem I've mentioned a while ago: The request is too big.

**Comment by leo** [comment]
@michaelwschultz How big was the image?

**Comment by michaelwschultz** [comment]
Just a screenshot. Probably 500k or so.

**Comment by leo** [comment]
Got it! Closing this because we're going to rework the whole uploading process completely (in order to add support for streaming stuff).
